-- =====================================================
-- Estructura de activos_ti (migrada desde Supabase)
-- Ejecutar en DBeaver conectado a la base activos_ti
-- (Alt+X = ejecutar script completo)
-- =====================================================

BEGIN;

-- ---------- Tablas base ----------

CREATE TABLE areas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar NOT NULL,
  nombre_normalizado text,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE personas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar NOT NULL,
  cargo varchar,
  correo varchar,
  area_id bigint REFERENCES areas(id),
  estado varchar DEFAULT 'Activo',
  documento text,
  area text,
  nombre_normalizado text,
  telefono text
);

CREATE TABLE activos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar NOT NULL UNIQUE,
  tipo varchar,
  marca varchar,
  modelo varchar,
  serial varchar,
  estado varchar,
  disponibilidad varchar,
  persona_id bigint REFERENCES personas(id) ON DELETE SET NULL,
  observaciones text,
  asignado_a text,
  area text,
  procesador text,
  ram_gb numeric,
  disco_gb numeric,
  sistema_operativo text,
  fecha_asignacion date,
  fecha_compra date,
  hostname text,
  usuario_windows text,
  uuid_equipo text,
  bios_serial text,
  dominio text,
  direccion_ip text,
  direccion_mac text,
  ultima_revision timestamptz,
  cantidad integer NOT NULL DEFAULT 1,
  activo_padre_id bigint REFERENCES activos(id),
  factura_ruta text,
  ram text,
  disco text,
  ip text,
  mac text,
  garantia text,
  proveedor varchar,
  precio_compra numeric,
  moneda text NOT NULL DEFAULT 'COP',
  nro_factura text,
  nro_orden text,
  centro_costo text,
  sede text,
  fecha_puesta_uso date,
  vida_util_meses integer,
  valor_residual numeric NOT NULL DEFAULT 0,
  garantia_inicio date,
  garantia_meses integer,
  garantia_fin date,
  CONSTRAINT chk_activos_precio CHECK (precio_compra IS NULL OR precio_compra >= 0),
  CONSTRAINT chk_activos_residual CHECK (valor_residual >= 0),
  CONSTRAINT chk_activos_vida CHECK (vida_util_meses IS NULL OR (vida_util_meses >= 1 AND vida_util_meses <= 600)),
  CONSTRAINT chk_activos_garantia_meses CHECK (garantia_meses IS NULL OR (garantia_meses >= 0 AND garantia_meses <= 240))
);

CREATE TABLE activos_adicionales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint REFERENCES activos(id) ON DELETE CASCADE,
  tipo text,
  descripcion text,
  factura_ruta text,
  created_at timestamptz DEFAULT now(),
  proveedor varchar,
  precio_compra numeric,
  nro_factura text
);

CREATE TABLE tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint REFERENCES activos(id),
  titulo varchar,
  descripcion text,
  estado varchar DEFAULT 'Pendiente',
  fecha timestamp DEFAULT now()
);

CREATE TABLE movimientos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint REFERENCES activos(id),
  persona_id bigint REFERENCES personas(id),
  accion varchar,
  fecha timestamp DEFAULT now(),
  observacion text
);

CREATE TABLE actas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id bigint,
  fecha timestamp DEFAULT now(),
  tipo varchar,
  pdf_url text,
  observaciones text,
  ruta_pdf text
);

CREATE TABLE historial (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint,
  usuario text,
  accion text,
  fecha timestamp DEFAULT now(),
  detalle text,
  usuario_id bigint,
  usuario_nombre text
);

-- ---------- Usuarios y permisos ----------

CREATE TABLE roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  descripcion text,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamptz DEFAULT now()
);

CREATE TABLE modulos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text NOT NULL UNIQUE,
  nombre text NOT NULL,
  descripcion text,
  orden integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE permisos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_id bigint NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  modulo_id bigint NOT NULL REFERENCES modulos(id) ON DELETE CASCADE,
  puede_ver boolean NOT NULL DEFAULT false,
  puede_crear boolean NOT NULL DEFAULT false,
  puede_editar boolean NOT NULL DEFAULT false,
  puede_eliminar boolean NOT NULL DEFAULT false,
  UNIQUE (rol_id, modulo_id)
);

CREATE TABLE usuarios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text,
  correo text UNIQUE,
  password text,
  rol text,
  password_hash text,
  rol_id bigint,
  activo boolean DEFAULT true,
  ultimo_acceso timestamptz,
  creado_en timestamptz DEFAULT now(),
  actualizado_en timestamptz DEFAULT now(),
  username text
);

-- ---------- Recolector de equipos ----------

CREATE TABLE tokens_recolector (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  token_hash text NOT NULL UNIQUE,
  activo boolean DEFAULT true,
  creado_en timestamptz DEFAULT now(),
  ultimo_uso timestamptz
);

CREATE TABLE escaneos_equipos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint REFERENCES activos(id) ON DELETE SET NULL,
  hostname text,
  usuario_windows text,
  bios_serial text,
  uuid_equipo text,
  marca text,
  modelo text,
  procesador text,
  ram_gb numeric,
  disco_gb numeric,
  sistema_operativo text,
  direccion_ip text,
  direccion_mac text,
  dominio text,
  version_recolector text,
  estado text DEFAULT 'nuevo',
  datos_json jsonb,
  fecha_escaneo timestamptz DEFAULT now()
);

CREATE TABLE cambios_hardware (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint REFERENCES activos(id) ON DELETE CASCADE,
  escaneo_id bigint REFERENCES escaneos_equipos(id) ON DELETE CASCADE,
  campo text,
  valor_anterior text,
  valor_nuevo text,
  estado_revision text DEFAULT 'Pendiente',
  fecha timestamptz DEFAULT now()
);

CREATE TABLE recolector_equipos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identificador text NOT NULL UNIQUE,
  hostname text,
  usuario_windows text,
  dominio text,
  marca text,
  modelo text,
  bios_serial text,
  uuid_equipo text,
  procesador text,
  ram_gb numeric,
  disco_gb numeric,
  sistema_operativo text,
  version_sistema text,
  arquitectura text,
  direccion_ip text,
  direccion_mac text,
  version_recolector text,
  discos jsonb,
  adaptadores jsonb,
  activo_id bigint REFERENCES activos(id),
  primera_conexion timestamptz DEFAULT now(),
  ultima_conexion timestamptz DEFAULT now()
);

-- ---------- Configuracion y catalogos ----------

CREATE TABLE configuracion (
  id integer NOT NULL PRIMARY KEY,
  nombre_empresa text NOT NULL,
  correo_soporte text,
  dias_alerta_garantia integer NOT NULL DEFAULT 30,
  sesion_minutos integer DEFAULT 30,
  exigir_serial boolean DEFAULT false,
  moneda_defecto text NOT NULL DEFAULT 'COP'
);

CREATE TABLE tipos_vida_util (
  tipo text PRIMARY KEY,
  vida_util_meses integer NOT NULL CHECK (vida_util_meses >= 1 AND vida_util_meses <= 600),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE historial_cambios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint NOT NULL REFERENCES activos(id) ON DELETE CASCADE,
  usuario_id integer,
  usuario_nombre text,
  campo text NOT NULL,
  valor_anterior text,
  valor_nuevo text,
  fecha timestamptz NOT NULL DEFAULT now()
);

-- ---------- Software, licencias, contratos ----------

CREATE TABLE software (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  fabricante text,
  version text NOT NULL DEFAULT '',
  categoria text,
  created_at timestamptz NOT NULL DEFAULT now(),
  activo boolean NOT NULL DEFAULT true,
  UNIQUE (nombre, version)
);

CREATE TABLE licencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  software_id bigint NOT NULL REFERENCES software(id) ON DELETE CASCADE,
  tipo text NOT NULL DEFAULT 'perpetua'
    CHECK (tipo IN ('perpetua','suscripcion','oem','volumen','open_source')),
  cantidad integer NOT NULL DEFAULT 1 CHECK (cantidad > 0),
  clave text,
  proveedor text,
  fecha_compra date,
  fecha_vence date,
  costo numeric,
  moneda text NOT NULL DEFAULT 'COP',
  activa boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE contratos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo text NOT NULL DEFAULT 'mantenimiento'
    CHECK (tipo IN ('mantenimiento','leasing','soporte','garantia_extendida','otro')),
  proveedor text NOT NULL,
  numero text,
  fecha_inicio date,
  fecha_fin date,
  costo numeric,
  moneda text NOT NULL DEFAULT 'COP',
  renovacion text NOT NULL DEFAULT 'manual'
    CHECK (renovacion IN ('manual','automatica','no_renueva')),
  notas text,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT contratos_fechas_ok CHECK (fecha_inicio IS NULL OR fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE TABLE documentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint REFERENCES activos(id) ON DELETE CASCADE,
  tipo text NOT NULL DEFAULT 'otro'
    CHECK (tipo IN ('factura','acta','manual','garantia','otro')),
  nombre_original text NOT NULL,
  ruta text NOT NULL,
  tamano_bytes bigint,
  subido_por_id integer,
  subido_por_nombre text,
  created_at timestamptz NOT NULL DEFAULT now(),
  eliminado_at timestamptz,
  eliminado_por text,
  contrato_id bigint REFERENCES contratos(id),
  licencia_id bigint REFERENCES licencias(id)
);

CREATE TABLE activo_software (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint NOT NULL REFERENCES activos(id) ON DELETE CASCADE,
  software_id bigint NOT NULL REFERENCES software(id) ON DELETE CASCADE,
  licencia_id bigint REFERENCES licencias(id) ON DELETE SET NULL,
  fecha_instalacion date NOT NULL DEFAULT CURRENT_DATE,
  instalado_por text,
  created_at timestamptz NOT NULL DEFAULT now(),
  eliminado_at timestamptz
);

CREATE TABLE activo_contrato (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint NOT NULL REFERENCES activos(id) ON DELETE CASCADE,
  contrato_id bigint NOT NULL REFERENCES contratos(id) ON DELETE CASCADE,
  vinculado_por text,
  created_at timestamptz NOT NULL DEFAULT now(),
  eliminado_at timestamptz
);

CREATE TABLE mantenimientos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id bigint NOT NULL REFERENCES activos(id) ON DELETE CASCADE,
  ticket_id bigint REFERENCES tickets(id) ON DELETE SET NULL,
  tipo text NOT NULL DEFAULT 'preventivo' CHECK (tipo IN ('preventivo','correctivo')),
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  tecnico text,
  costo numeric,
  moneda text NOT NULL DEFAULT 'COP',
  descripcion text NOT NULL,
  proximo_mantenimiento date,
  registrado_por text,
  created_at timestamptz NOT NULL DEFAULT now(),
  eliminado_at timestamptz,
  contrato_id bigint REFERENCES contratos(id),
  proveedor text,
  CONSTRAINT mant_proximo_ok CHECK (proximo_mantenimiento IS NULL OR proximo_mantenimiento >= fecha)
);

CREATE TABLE retiros_personas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id bigint NOT NULL REFERENCES personas(id) ON DELETE CASCADE,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  motivo text NOT NULL,
  notas text,
  usuario_id bigint,
  usuario_nombre text,
  reactivado_en timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMIT;

-- =====================================================
-- EJECUTAR ESTE BLOQUE DESPUES DE IMPORTAR LOS DATOS
-- Ajusta los contadores de id para que los registros
-- nuevos no choquen con los importados.
-- =====================================================
/*
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT c.table_name, c.column_name
    FROM information_schema.columns c
    WHERE c.table_schema = 'public' AND c.column_name = 'id'
      AND pg_get_serial_sequence(quote_ident(c.table_name), 'id') IS NOT NULL
  LOOP
    EXECUTE format(
      'SELECT setval(pg_get_serial_sequence(%L, %L), COALESCE((SELECT MAX(id) FROM %I), 0) + 1, false)',
      r.table_name, r.column_name, r.table_name);
  END LOOP;
END $$;
*/
